/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutAdminIndexImport } from './routes/_layout/admin/index'
import { Route as LayoutAdminDeploymentDeployIdImport } from './routes/_layout/admin/deployment/$deployId'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LayoutAdminIndexRoute = LayoutAdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminDeploymentDeployIdRoute =
  LayoutAdminDeploymentDeployIdImport.update({
    id: '/admin/deployment/$deployId',
    path: '/admin/deployment/$deployId',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/admin/deployment/$deployId': {
      id: '/_layout/admin/deployment/$deployId'
      path: '/admin/deployment/$deployId'
      fullPath: '/admin/deployment/$deployId'
      preLoaderRoute: typeof LayoutAdminDeploymentDeployIdImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
  LayoutAdminDeploymentDeployIdRoute: typeof LayoutAdminDeploymentDeployIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
  LayoutAdminDeploymentDeployIdRoute: LayoutAdminDeploymentDeployIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '': typeof LayoutRouteWithChildren
  '/admin': typeof LayoutAdminIndexRoute
  '/admin/deployment/$deployId': typeof LayoutAdminDeploymentDeployIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '': typeof LayoutRouteWithChildren
  '/admin': typeof LayoutAdminIndexRoute
  '/admin/deployment/$deployId': typeof LayoutAdminDeploymentDeployIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/admin/': typeof LayoutAdminIndexRoute
  '/_layout/admin/deployment/$deployId': typeof LayoutAdminDeploymentDeployIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/admin' | '/admin/deployment/$deployId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/admin' | '/admin/deployment/$deployId'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/admin/'
    | '/_layout/admin/deployment/$deployId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/admin/",
        "/_layout/admin/deployment/$deployId"
      ]
    },
    "/_layout/admin/": {
      "filePath": "_layout/admin/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/admin/deployment/$deployId": {
      "filePath": "_layout/admin/deployment/$deployId.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
